add factory for adw::PreferencePage
Relm4/Relm4 pull request #358
Opened 2022-11-27 21:04 UTC by tronta

#### Summary

My first try to add a factory

#### Checklist

- [ ] cargo fmt
- [ ] cargo clippy
- [ ] cargo test
- [ ] updated CHANGES.md

2022-11-27 21:07 UTC, tronta commented
Hi @AaronErhardt , I tried a little to add this factory.
Maybe you can give some hints how to implement properly. Thanks

2022-11-27 21:12 UTC, AaronErhardt requested changes
Looks good overall.

2022-11-27 21:12 UTC, AaronErhardt commented on relm4/src/factory/widgets/libadwaita.rs
> +        *(&widget).as_ref()
Can't you simply use `widget.as_ref().clone()` at the end?

2022-11-27 21:12 UTC, AaronErhardt commented on relm4/src/factory/widgets/libadwaita.rs
> +        *(&widget).as_ref()
You can recycle `factory_append()` here, at least that saves one line of code.

2022-11-28 06:10 UTC, tronta commented
Cool thanks. One problem still remains… Maybe you have an other hint :smile:

2022-11-28 08:51 UTC, AaronErhardt commented
> One problem still remains

What do you mean? Looks good to me.

2022-11-28 09:38 UTC, AaronErhardt commented on relm4/src/factory/widgets/libadwaita.rs
> +        widget.as_ref().clone()
Btw. you can also re-use the `prepend()` method here.

2022-11-29 19:25 UTC, tronta commented
Hi @AaronErhardt, what do you think is the best way to go forward here in order to merge it?
In parallel I'm writing a small app which uses this feature where I can test it… with the upcoming Advent of Code and other stuff I'm probably pretty busy :smile: 

Do you think it is ready for review now, or do you think I should wait till I have tested it with an real implementation?

2022-11-29 19:35 UTC, AaronErhardt commented
I'm pretty confident that your implementation is correct. And we're still in a beta state officially, so even if there were some minor concerns I wouldn't be afraid of merging this.

2022-12-04 09:57 UTC, AaronErhardt requested changes

2022-12-04 09:57 UTC, AaronErhardt commented on CHANGES.md
> ++ core. Support factories with adw::PreferencePage
Can you move this to "Unreleased"?

2022-12-04 21:31 UTC, AaronErhardt approved these changes
Thanks!

2022-12-04 21:31 UTC, merged