Prevent leaking CommandSenderInner struct
Relm4/Relm4 pull request #379
Opened 2022-12-24 09:27 UTC by Ayush1325

#### Summary
Earlier, this struct was being leaked due to the implementation of Deref. However, since the struct was never actually exported, documentation was not being generated for it's method.

This commit just makes the struct private and instead creates wrapper functions over it. This is typically whats done in Rust std.

Signed-off-by: Ayush Singh <ayushsingh1325@gmail.com>

#### Checklist

- [x] cargo fmt
- [x] cargo clippy
- [x] cargo test
- [ ] updated CHANGES.md

2022-12-24 17:31 UTC, euclio approved these changes

2022-12-26 19:43 UTC, AaronErhardt requested changes
Looks good. Could you add an entry for this to the changelog in the category "Fixed"?

2022-12-27 03:49 UTC, Ayush1325 commented
> Looks good. Could you add an entry for this to the changelog in the category "Fixed"?

Should I add a new Release as well, or just add the changes to `0.5.0-rc.1`?

2022-12-27 08:00 UTC, AaronErhardt commented
Just put a `### Fixed` below `## Unreleased `. We collect changes under Unreleased until a new version comes out.

2022-12-27 16:01 UTC, AaronErhardt approved these changes
Thanks!

2022-12-27 16:01 UTC, merged